# = This is the API documentation for paru generated by RDoc.
# 
# Paru is a simple Ruby wrapper around {pandoc}[http://www.pandoc.org], the
# great multi-format document converter. Paru supports automating pandoc by
# writing Ruby programs and using pandoc in your Ruby programs. Paru also
# supports writing pandoc filters in Ruby. In {paru's user
# manual}[https://heerdebeer.org/Software/markdown/paru/] the use of paru is
# explained in detail, from explaining how to install and use paru, creating
# and using filters, to putting it all together in a real-world use case like
# generating that manual page.
#
# This document, however, describes paru's API.
#
# == Licence
#
# Copyright 2015, 2016 Huub de Beer <Huub@heerdebeer.org>
#
# This file is part of Paru
#
# Paru is free software: you can redistribute it and/or modify it under the
# terms of the GNU General Public License as published by the Free Software
# Foundation, either version 3 of the License, or (at your option) any later
# version.
#
# Paru is distributed in the hope that it will be useful, but WITHOUT ANY
# WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
# FOR A PARTICULAR PURPOSE.  See the GNU General Public License for more
# details.
#
# You should have received a copy of the GNU General Public License along with
# Paru.  If not, see <http://www.gnu.org/licenses/>.

require "paru/pandoc"
require "paru/error"
require "paru/filter"
