name: Ruby

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    name: Ruby ${{ matrix.ruby }}
    strategy:
      matrix:
        ruby: [3.3.5]
        pandoc: [3.4]

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby }}
        bundler-cache: true

    - name: Set up Pandoc
      uses: r-lib/actions/setup-pandoc@v2
      with:
        pandoc-version: ${{ matrix.pandoc }}

    - name: Run tests
      run: bundle exec rake test
